### ISSUE TITLE
Верстка страниц ошибок

### ISSUE THREAD

**Issue by Redvoronik** [extiser/svadbavo-2015#15]
https://www.dropbox.com/s/cmu1sq495n0a5ff/PSD_svadba_error.rar?dl=0
тут псд для страниц 404, страницы ошибки 
и добавлены модалки примеров карточек, которые должны появляться при клике по ссылке "Пример карточки" 
на страницах
cabinet-service.html
http://take.ms/qpFir
advertise.html
http://take.ms/Jz7jH

**Comment by extiser** [comment]
сделано
